INSERT INTO PIECES (TYPE_PIECE, PRIX_PIECE, CATEGORIE_PIECE) VALUES ('Plaquettes de frein', 19.9, 'Freinage'),
			  ('Disques de freinage', 89.9, 'Freinage'),
			  ('Cylindres de freinage', 49.9 , 'Freinage'),
			  ('Embrayage', 69.9, 'Embrayage'),
			  ('Fourchette d\'embrayage', 19.9, 'Embrayage'),
			  ('Filtre d\'habitacle', 14.9, 'Filtration'),	
			  ('Filtre a huile', 6.9, 'Filtration'),
			  ('Amortisseurs', 69.9, 'Suspension'),	
			  ('Kit amortisseur', 19.9, 'Suspension'),
			  ('Rotules', 39.9, 'Suspension'),
			  ('Pot d\'echappement', 89.9, 'Echappement'),
			  ('Lampes', 29.9, 'Eclairage');


#INSERT INTO OPERATIONS VALUES ('Vidange',prix,duree),
#			      ('Revision', , ),
#			      (' ', , ),
#			      (' ', , ),
#			      (' ', , ),
#			      (' ', , ),
#			      (' ', , ),
#			      (' ', , );

INSERT INTO PARTICULIERS (CIVILITE_PARTICULIER, NOM_PARTICULIER, PRENOM_PARTICULIER, DATENAISS_PARTICULIER, ADR_CLIENT, CP_CLIENT, VILLE_CLIENT, MAIL_CLIENT, TEL_CLIENT, MDP_CLIENT, ETAT_CLIENT) VALUES ('Homme', 'ADMIN', '', '0001-01-01','ADMIN', '75000', 'Paris', 'ADMIN@ADMIN', '00000000001', sha1(sha1('ADMIN')), '1'),
				('Femme', '1', 'User', '1996-11-02','21 Boulevard Francois Mitterand', '75000', 'Paris', 'user1@gmail.com', '0138435898', sha1(sha1('user1')), '1'),
				('Homme', '2', 'User', '1987-12-13','38 Boulevard Haussmann', '75000', 'Paris', 'user2@gmail.com', '0181437898', sha1(sha1('user2')), '1'),
				('Homme', 'Mauer', 'Pierre', '1992-11-25', '2, rue Jean-François Gerbillon', '75006', 'Paris', 'mauerpierre@gmail.com', '0680631639', sha1(sha1('123456')), '1');

INSERT INTO TYPEVEHICULES (MARQUE_VEHICULE, MODELE_VEHICULE) VALUES ('Audi','A1'),
				 ('Audi','A2'),
				 ('Audi','A3'),
				 ('Audi','Q2'),
				 ('Audi','Q3'),
				 ('Audi','R8'),
				 ('Dacia','Duster'),
				 ('Dacia','Logan'),
				 ('Dacia','Sandero'),
				 ('Dacia','Lodgy'),
				 ('Dacia','Dokker'),
				 ('Ford','Fiesta'),
				 ('Ford','Focus'),
				 ('Ford','Galaxy'),
				 ('Ford','Ka'),
				 ('Ford','Mondeo'),
				 ('Fiat','500'),
				 ('Fiat','500 L'),
				 ('Fiat','500 X'),
				 ('Fiat','Punto'),
				 ('Fiat','Panda'),
				 ('Hyundai','I10'),
				 ('Hyundai','I20'),
				 ('Hyundai','I30'),
				 ('Hyundai','I40'),
				 ('Hyundai','Ioniq'),
				 ('Kia','Niro'),
				 ('Kia','Picanto'),
				 ('Kia','Rio'),
				 ('Kia','Sportage'),
				 ('Kia','Venga'),
				 ('Mercedes','Classe A'),
				 ('Mercedes','Classe B'),
				 ('Mercedes','Classe C'),
				 ('Mercedes','Classe E'),
				 ('Mercedes','Classe S'),
				 ('Nissan','Juke'),
				 ('Nissan','Micra'),
				 ('Nissan','Note'),
				 ('Nissan','Pulsar'),
				 ('Nissan','Qashqai'),
				 ('Opel','Adam'),
				 ('Opel','Astra'),
				 ('Opel','Corsa'),
				 ('Opel','Meriva'),
				 ('Opel','Zafira'),
				 ('Peugeot','108'),
				 ('Peugeot','207'),
				 ('Peugeot','2008'),
				 ('Peugeot','308'),
				 ('Peugeot','Traveller'),
				 ('Renault','Captur'),
				 ('Renault','Clio'),
				 ('Renault','Espace'),
				 ('Renault','Kadjar'),
				 ('Renault','Megane'),
				 ('Renault','Scenic'),
				 ('Renault','Twingo'),
				 ('Smart','Forfour'),
				 ('Smart','Fortwo'),
				 ('Toyota','Auris'),
				 ('Toyota','Aygo'),
				 ('Toyota','Iq'),
				 ('Toyota','Verso'),
				 ('Toyota','Yaris'),
				 ('Volkswagen','Cc'),
				 ('Volkswagen','Coccinelle'),
				 ('Volkswagen','Golf'),
				 ('Volkswagen','Passat'),
				 ('Volkswagen','Polo'),
				 ('Volkswagen','Tiguan'),
				 ('Volkswagen','Up!');
