INSERT INTO PIECES VALUES (NULL,'Amortisseurs',69,9),
			  (NULL,'Bloc optique',39.9),
			  (NULL,'Batterie',59.9),
			  (NULL,'Pot d\'echappement',89.9),
			  (NULL,'Filtre d’habitacle',14.9),
			  (NULL,'Filtre à carburant',1.9),	
			  (NULL,'Filtre à huile',6.9),
			  (NULL,'Disques de frein',89.9),	
			  (NULL,'Plaquettes de frein',19.9),
			  (NULL,'Moteur complet',149.9),
			  (NULL,'Embrayage',64.9),
			  (NULL,'Pneumatiques',49.9),
			  (NULL,'Essuie-glace',5.9),
			  (NULL,'Courroie de distribution',69.9);

#INSERT INTO OPERATIONS VALUES ('Vidange',prix,duree),
#			      ('Revision', , ),
#			      (' ', , ),
#			      (' ', , ),
#			      (' ', , ),
#			      (' ', , ),
#			      (' ', , ),
#			      (' ', , );

INSERT INTO PARTICULIERS VALUES (NULL,'Homme', 'ADMIN', '', '0000-00-00','ADMIN', '75000', 'Paris', 'ADMIN@ADMIN', '00000000001', sha1(sha1('ADMIN')), '1'),
				(NULL,'Femme', '1', 'User', '1996-11-02','21 Boulevard Francois Mitterand', '75000', 'Paris', 'user1@gmail.com', '0138435898', sha1(sha1('user1')), '1'),
				(NULL,'Homme', '2', 'User', '1987-12-13','38 Boulevard Haussmann', '75000', 'Paris', 'user2@gmail.com', '0181437898', sha1(sha1('user2')), '1');

INSERT INTO TYPEVEHICULES VALUES (NULL,'Audi','A1'),
				 (NULL,'Audi','A2'),
				 (NULL,'Audi','A3'),
				 (NULL,'Audi','Q2'),
				 (NULL,'Audi','Q3'),
				 (NULL,'Audi','R8'),
				 (NULL,'Dacia','Duster'),
				 (NULL,'Dacia','Logan'),
				 (NULL,'Dacia','Sandero'),
				 (NULL,'Dacia','Lodgy'),
				 (NULL,'Dacia','Dokker'),
				 (NULL,'Ford','Fiesta'),
				 (NULL,'Ford','Focus'),
				 (NULL,'Ford','Galaxy'),
				 (NULL,'Ford','Ka'),
				 (NULL,'Ford','Mondeo'),
				 (NULL,'Fiat','500'),
				 (NULL,'Fiat','500 L'),
				 (NULL,'Fiat','500 X'),
				 (NULL,'Fiat','Punto'),
				 (NULL,'Fiat','Panda'),
				 (NULL,'Hyundai','I10'),
				 (NULL,'Hyundai','I20'),
				 (NULL,'Hyundai','I30'),
				 (NULL,'Hyundai','I40'),
				 (NULL,'Hyundai','Ioniq'),
				 (NULL,'Kia','Niro'),
				 (NULL,'Kia','Picanto'),
				 (NULL,'Kia','Rio'),
				 (NULL,'Kia','Sportage'),
				 (NULL,'Kia','Venga'),
				 (NULL,'Mercedes','Classe A'),
				 (NULL,'Mercedes','Classe B'),
				 (NULL,'Mercedes','Classe C'),
				 (NULL,'Mercedes','Classe E'),
				 (NULL,'Mercedes','Classe S'),
				 (NULL,'Nissan','Juke'),
				 (NULL,'Nissan','Micra'),
				 (NULL,'Nissan','Note'),
				 (NULL,'Nissan','Pulsar'),
				 (NULL,'Nissan','Qashqai'),
				 (NULL,'Opel','Adam'),
				 (NULL,'Opel','Astra'),
				 (NULL,'Opel','Corsa'),
				 (NULL,'Opel','Meriva'),
				 (NULL,'Opel','Zafira'),
				 (NULL,'Peugeot','108'),
				 (NULL,'Peugeot','207'),
				 (NULL,'Peugeot','2008'),
				 (NULL,'Peugeot','308'),
				 (NULL,'Peugeot','Traveller'),
				 (NULL,'Renault','Captur'),
				 (NULL,'Renault','Clio'),
				 (NULL,'Renault','Espace'),
				 (NULL,'Renault','Kadjar'),
				 (NULL,'Renault','Megane'),
				 (NULL,'Renault','Scenic'),
				 (NULL,'Renault','Twingo'),
				 (NULL,'Smart','Forfour'),
				 (NULL,'Smart','Fortwo'),
				 (NULL,'Toyota','Auris'),
				 (NULL,'Toyota','Aygo'),
				 (NULL,'Toyota','Iq'),
				 (NULL,'Toyota','Verso'),
				 (NULL,'Toyota','Yaris'),
				 (NULL,'Volkswagen','Cc'),
				 (NULL,'Volkswagen','Coccinelle'),
				 (NULL,'Volkswagen','Golf'),
				 (NULL,'Volkswagen','Passat'),
				 (NULL,'Volkswagen','Polo'),
				 (NULL,'Volkswagen','Tiguan'),
				 (NULL,'Volkswagen','Up!');
