/* TRIGGER HERITAGE CLIENTS + VEHICULES
	TRIGGER QUI INCREMENTE AUTOMATIQUEMENT LE NOMBRE D'INTERVENTION 
		CHAQUE TECHNICIEN. 
	TRIGGER QUI VERIFIE LA DISPO D'UN TECHNICIEN
	TRIGGER QUI PERMET DE CALCULER AUTOMATIQUEMENT LE MONTANT TOTAL 
		DE LA FACTURE
	TRIGGER QUI PERMET DE GERER LES STOCKS DES PIECES 
*/ 
use garage;
DROP TRIGGER IF EXISTS AjoutParticuliers; 
DELIMITER // 
CREATE TRIGGER AjoutParticuliers
	BEFORE INSERT
	ON PARTICULIERS
	FOR EACH ROW 

	BEGIN 
		DECLARE nbC, nbE int; 

		SELECT COUNT(*) INTO nbC FROM CLIENTS WHERE ID_CLIENT = new.ID_CLIENT;

		IF nbC = 0 THEN 
			INSERT INTO CLIENTS VALUES(new.ID_CLIENT, new.ADR_CLIENT, new.CP_CLIENT, new.VILLE_CLIENT, new.MAIL_CLIENT, new.TEL_CLIENT, new.MDP_CLIENT, new.ETAT_CLIENT); 
		END IF; 

		SELECT COUNT(*) INTO nbE FROM ENTREPRISES WHERE ID_CLIENT = new.ID_CLIENT;

		IF nbE > 0 THEN 
			SIGNAL SQLSTATE '45000'
			SET Message_text = 'ENTREPRISES';
		END IF; 
	END // 
DELIMITER ;

DROP TRIGGER IF EXISTS AjoutEntreprises; 
DELIMITER // 
CREATE TRIGGER AjoutEntreprises
	BEFORE INSERT
	ON ENTREPRISES
	FOR EACH ROW 

	BEGIN 
		DECLARE nbC, nbP int; 

		SELECT COUNT(*) INTO nbC FROM CLIENTS WHERE ID_CLIENT = new.ID_CLIENT;

		IF nbC = 0 THEN 
			INSERT INTO CLIENTS VALUES(new.ID_CLIENT, new.ADR_CLIENT, new.CP_CLIENT, new.VILLE_CLIENT, new.MAIL_CLIENT, new.TEL_CLIENT, new.MDP_CLIENT, new.ETAT_CLIENT); 
		END IF; 

		SELECT COUNT(*) INTO nbP FROM PARTICULIERS WHERE ID_CLIENT = new.ID_CLIENT;

		IF nbP > 0 THEN 
			SIGNAL SQLSTATE '45000'
			SET Message_text = 'PARTICULIERS';
		END IF; 
	END // 
DELIMITER ;

DROP TRIGGER IF EXISTS updateParticuliers;
Delimiter //
CREATE TRIGGER updateParticuliers
	BEFORE UPDATE
	ON PARTICULIERS
	FOR EACH ROW

	BEGIN
		UPDATE CLIENTS SET ID_CLIENT = new.ID_CLIENT, ADR_CLIENT = new.ADR_CLIENT, CP_CLIENT = new.CP_CLIENT, VILLE_CLIENT = new.VILLE_CLIENT, MAIL_CLIENT = new.MAIL_CLIENT, TEL_CLIENT = new.TEL_CLIENT, MDP_CLIENT = new.MDP_CLIENT, ETAT_CLIENT = new.ETAT_CLIENT WHERE ID_CLIENT = old.ID_CLIENT;
END //
Delimiter ;

DROP TRIGGER IF EXISTS updateEntreprises;
Delimiter //
CREATE TRIGGER updateEntreprises
	BEFORE UPDATE
	ON ENTREPRISES
	FOR EACH ROW

	BEGIN
		UPDATE CLIENTS SET ID_CLIENT = new.ID_CLIENT, ADR_CLIENT = new.ADR_CLIENT, CP_CLIENT = new.CP_CLIENT, VILLE_CLIENT = new.VILLE_CLIENT, MAIL_CLIENT = new.MAIL_CLIENT, TEL_CLIENT = new.TEL_CLIENT, MDP_CLIENT = new.MDP_CLIENT, ETAT_CLIENT = new.ETAT_CLIENT WHERE ID_CLIENT = old.ID_CLIENT;
END //
Delimiter ;

DROP TRIGGER IF EXISTS deleteParticuliers; 
Delimiter // 
CREATE TRIGGER deleteParticuliers
	BEFORE DELETE 
	ON PARTICULIERS
	FOR EACH ROW

	BEGIN
		DELETE FROM CLIENTS WHERE ID_CLIENT = OLD.ID_CLIENT; 
END // 
DELIMITER ; 

DROP TRIGGER IF EXISTS deleteEntreprises;  
Delimiter // 
CREATE TRIGGER deleteEntreprises
	BEFORE DELETE 
	ON ENTREPRISES
	FOR EACH ROW

	BEGIN
		DELETE FROM CLIENTS WHERE ID_CLIENT = OLD.ID_CLIENT; 
END // 
DELIMITER ; 

DROP TRIGGER IF EXISTS coeffVehicule; 
DELIMITER // 
CREATE TRIGGER coeffVehicule
	BEFORE INSERT
	ON TYPEVEHICULES
	FOR EACH ROW 

	BEGIN
		IF new.marque_Vehicule = 'Audi' THEN 
			SET new.COEFF_VEHICULE = 1.9;
		ELSEIF new.marque_Vehicule = 'Dacia' THEN
			SET new.COEFF_VEHICULE = 1.1;
		ELSEIF new.marque_Vehicule = 'Ford' THEN
			SET new.COEFF_VEHICULE = 1.7;
		ELSEIF new.marque_Vehicule = 'Fiat' THEN
			SET new.COEFF_VEHICULE = 1.3;
		ELSEIF new.marque_Vehicule = 'Hyundai' THEN
			SET new.COEFF_VEHICULE = 1.6;
		ELSEIF new.marque_Vehicule = 'Kia' THEN
			SET new.COEFF_VEHICULE = 1.4;
		ELSEIF new.marque_Vehicule = 'Mercedes' THEN
			SET new.COEFF_VEHICULE = 2.0;
		ELSEIF new.marque_Vehicule = 'Nissan' THEN
			SET new.COEFF_VEHICULE = 1.5;
		ELSEIF new.marque_Vehicule = 'Opel' THEN
			SET new.COEFF_VEHICULE = 1.2;
		ELSEIF new.marque_Vehicule = 'Peugeot' THEN
			SET new.COEFF_VEHICULE = 1.5;
		ELSEIF new.marque_Vehicule = 'Renault' THEN
			SET new.COEFF_VEHICULE = 1.0;
		ELSEIF new.marque_Vehicule = 'Smart' THEN
			SET new.COEFF_VEHICULE = 1.4;
		ELSEIF new.marque_Vehicule = 'Toyota' THEN
			SET new.COEFF_VEHICULE = 1.7;
		ELSEIF new.marque_Vehicule = 'Volkswagen' THEN
			SET new.COEFF_VEHICULE = 1.8;
		END IF;
	END // 
DELIMITER ;
